//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18408
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserInfo", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary")]
    public partial class UserInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AgeField;
        
        private string NameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age
        {
            get
            {
                return this.AgeField;
            }
            set
            {
                this.AgeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegisteredUserInfo", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary")]
    public partial class RegisteredUserInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ServerIdField;
        
        private WcfServiceLibrary.UserInfo UserInfoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ServerId
        {
            get
            {
                return this.ServerIdField;
            }
            set
            {
                this.ServerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfServiceLibrary.UserInfo UserInfo
        {
            get
            {
                return this.UserInfoField;
            }
            set
            {
                this.UserInfoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UploadedFileInfo", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary")]
    public partial class UploadedFileInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long FileSizeField;
        
        private int ServerIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long FileSize
        {
            get
            {
                return this.FileSizeField;
            }
            set
            {
                this.FileSizeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ServerId
        {
            get
            {
                return this.ServerIdField;
            }
            set
            {
                this.ServerIdField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IStatelessService")]
public interface IStatelessService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatelessService/GetServerId", ReplyAction="http://tempuri.org/IStatelessService/GetServerIdResponse")]
    int GetServerId();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatelessService/GetServerId", ReplyAction="http://tempuri.org/IStatelessService/GetServerIdResponse")]
    System.Threading.Tasks.Task<int> GetServerIdAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatelessService/RegisterUser", ReplyAction="http://tempuri.org/IStatelessService/RegisterUserResponse")]
    WcfServiceLibrary.RegisteredUserInfo RegisterUser(WcfServiceLibrary.UserInfo userInfo);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatelessService/RegisterUser", ReplyAction="http://tempuri.org/IStatelessService/RegisterUserResponse")]
    System.Threading.Tasks.Task<WcfServiceLibrary.RegisteredUserInfo> RegisterUserAsync(WcfServiceLibrary.UserInfo userInfo);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatelessService/UploadFile", ReplyAction="http://tempuri.org/IStatelessService/UploadFileResponse")]
    WcfServiceLibrary.UploadedFileInfo UploadFile(System.IO.Stream fileStream);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatelessService/UploadFile", ReplyAction="http://tempuri.org/IStatelessService/UploadFileResponse")]
    System.Threading.Tasks.Task<WcfServiceLibrary.UploadedFileInfo> UploadFileAsync(System.IO.Stream fileStream);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatelessService/DownloadFile", ReplyAction="http://tempuri.org/IStatelessService/DownloadFileResponse")]
    System.IO.Stream DownloadFile();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatelessService/DownloadFile", ReplyAction="http://tempuri.org/IStatelessService/DownloadFileResponse")]
    System.Threading.Tasks.Task<System.IO.Stream> DownloadFileAsync();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IStatelessServiceChannel : IStatelessService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class StatelessServiceClient : System.ServiceModel.ClientBase<IStatelessService>, IStatelessService
{
    
    public StatelessServiceClient()
    {
    }
    
    public StatelessServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public StatelessServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public StatelessServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public StatelessServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public int GetServerId()
    {
        return base.Channel.GetServerId();
    }
    
    public System.Threading.Tasks.Task<int> GetServerIdAsync()
    {
        return base.Channel.GetServerIdAsync();
    }
    
    public WcfServiceLibrary.RegisteredUserInfo RegisterUser(WcfServiceLibrary.UserInfo userInfo)
    {
        return base.Channel.RegisterUser(userInfo);
    }
    
    public System.Threading.Tasks.Task<WcfServiceLibrary.RegisteredUserInfo> RegisterUserAsync(WcfServiceLibrary.UserInfo userInfo)
    {
        return base.Channel.RegisterUserAsync(userInfo);
    }
    
    public WcfServiceLibrary.UploadedFileInfo UploadFile(System.IO.Stream fileStream)
    {
        return base.Channel.UploadFile(fileStream);
    }
    
    public System.Threading.Tasks.Task<WcfServiceLibrary.UploadedFileInfo> UploadFileAsync(System.IO.Stream fileStream)
    {
        return base.Channel.UploadFileAsync(fileStream);
    }
    
    public System.IO.Stream DownloadFile()
    {
        return base.Channel.DownloadFile();
    }
    
    public System.Threading.Tasks.Task<System.IO.Stream> DownloadFileAsync()
    {
        return base.Channel.DownloadFileAsync();
    }
}
