//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18408
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IStatefulService", CallbackContract = typeof(IStatefulServiceCallback), SessionMode = System.ServiceModel.SessionMode.Required)]
public interface IStatefulService
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IStatefulService/Start", ReplyAction = "http://tempuri.org/IStatefulService/StartResponse")]
    void Start(double initValue);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IStatefulService/Start", ReplyAction = "http://tempuri.org/IStatefulService/StartResponse")]
    System.Threading.Tasks.Task StartAsync(double initValue);

    [System.ServiceModel.OperationContractAttribute(IsInitiating = false, Action = "http://tempuri.org/IStatefulService/AddTo", ReplyAction = "http://tempuri.org/IStatefulService/AddToResponse")]
    void AddTo(double n);

    [System.ServiceModel.OperationContractAttribute(IsInitiating = false, Action = "http://tempuri.org/IStatefulService/AddTo", ReplyAction = "http://tempuri.org/IStatefulService/AddToResponse")]
    System.Threading.Tasks.Task AddToAsync(double n);

    [System.ServiceModel.OperationContractAttribute(IsTerminating = true, IsInitiating = false, Action = "http://tempuri.org/IStatefulService/Stop", ReplyAction = "http://tempuri.org/IStatefulService/StopResponse")]
    void Stop();

    [System.ServiceModel.OperationContractAttribute(IsTerminating = true, IsInitiating = false, Action = "http://tempuri.org/IStatefulService/Stop", ReplyAction = "http://tempuri.org/IStatefulService/StopResponse")]
    System.Threading.Tasks.Task StopAsync();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IStatefulServiceCallback
{

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://tempuri.org/IStatefulService/Equals")]
    void Equals(double result);

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://tempuri.org/IStatefulService/Equation")]
    void Equation(string eqn);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IStatefulServiceChannel : IStatefulService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class StatefulServiceClient : System.ServiceModel.DuplexClientBase<IStatefulService>, IStatefulService
{

    public StatefulServiceClient(System.ServiceModel.InstanceContext callbackInstance) :
        base(callbackInstance)
    {
    }

    public StatefulServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) :
        base(callbackInstance, endpointConfigurationName)
    {
    }

    public StatefulServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) :
        base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }

    public StatefulServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
        base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }

    public StatefulServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
        base(callbackInstance, binding, remoteAddress)
    {
    }

    public void Start(double initValue)
    {
        base.Channel.Start(initValue);
    }

    public System.Threading.Tasks.Task StartAsync(double initValue)
    {
        return base.Channel.StartAsync(initValue);
    }

    public void AddTo(double n)
    {
        base.Channel.AddTo(n);
    }

    public System.Threading.Tasks.Task AddToAsync(double n)
    {
        return base.Channel.AddToAsync(n);
    }

    public void Stop()
    {
        base.Channel.Stop();
    }

    public System.Threading.Tasks.Task StopAsync()
    {
        return base.Channel.StopAsync();
    }
}